name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '23.2'

    - run: npm install

    - name: Run Lint
      run: npm run lint

    - name: Run Prettier
      run: npm run format --write

    - name: Run Tests
      run: npm test
